IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'Teacher')
BEGIN
	CREATE TABLE Teacher(
		[Id] 			BIGINT PRIMARY KEY Identity(1,1),
		[Name] 			VARCHAR(50) NOT NULL,
		[Subject] 	    VARCHAR(10) NOT NULL
	)
END
GO

