IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'Student')
BEGIN
	CREATE TABLE Student(
		[Id] 			BIGINT PRIMARY KEY Identity(1,1),
		[Name] 			VARCHAR(50) NOT NULL,
		[RollNumber] 	VARCHAR(10) NOT NULL,
		[Standard] 		VARCHAR(15) NOT NULL
	)
END
GO

